[tool.poetry]
name = "shrt"
version = "0.1.0"
description = "Shorten URLs"
authors = ["Yehuda Deutsch <yeh@uda.co.il>"]
maintainers = ["Yehuda Deutsch <yeh@uda.co.il>"]
readme = "README.md"
repository = "https://gitlab.com/uda/shrt"
license = "MIT"

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/uda/shrt/-/issues"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = { extras = ["all"], version = "^0.79.0" }
typer = "^0.6.1"
fastapi-jinja = "^0.2.0"
SQLAlchemy = "^1.4.40"
databases = { extras = ["aiosqlite"], version = "^0.6.0" }
tabulate = "^0.8.10"

[tool.poetry.dev-dependencies]
dunamai = "^1.12.0"

[tool.poetry.scripts]
shrt = 'shrt.cli.main:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
