[tool.poetry]
name = "dfisher_2022a"
version = "v0.1.22"
description = "Spectral analysis code created for the delivery of the DFisher_2022A ADACS MAP project."
authors = [
            "J. Hu <jitinghu@swin.edu.au>", 
            "Gregory Poole <gbpoole@gmail.com>"
            ]
license = "MIT-expat"

readme = "README.md"

packages = [
    { include = "dfisher_2022a", from = "python" }
]

homepage = "https://github.com/ADACS-Australia/dfisher_2022a"
documentation = "https://dfisher-2022a.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = " >=3.8,<3.10"
Sphinx = { version = "4.2.0", optional = true }
sphinx-rtd-theme = { version = "1.0.0", optional = true }
numpy = "^1.8"
pandas = "^1.4.2"
mpdaf = "^3.5"
tables = "^3.7.0"
lmfit = "^1.0.3"
#lmfit = {git = "https://github.com/ADACS-Australia/light-lmfit-py.git", branch = "light"}
tqdm = "^4.64.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
pytest-cov = "^3.0.0"
viztracer = "^0.15.2"
py-spy = "^0.3.12"
line-profiler = "^3.5.1"
memory-profiler = "^0.60.0"
snakeviz = "^2.1.1"
black = "^22.3.0"
isort = "^5.10.1"
graphviz = "^0.20"
gprof2dot = "^2021.2.21"
ipykernel = "^6.13.0"
jupyter-contrib-nbextensions = "^0.5.1"
myst-parser = "^0.18.0"
sphinx-rtd-theme = "^1.0.0"


[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
