[tool.poetry]
authors = ["Craig Trim <craigtrim@gmail.com>"]
description = "Helper Microservice when a MongoDB Cloud instance is required."
name = "mongodb-cloud-helper"
version = "0.1.0"

[tool.poetry.dependencies]
baseblock = "*"
python = "3.8.5"

[tool.poetry.dev-dependencies]
autopep8 = "*"
pytest = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
