[tool.poetry]
name = "severino"
version = "0.8.5"
description = "O Severino é utilizado para facilitar as integrações e também a reutilização de código"
authors = ["Stone People Analytics <systems-techpeople@stone.com.br>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
Jinja2 = "^3.1.2"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
