[tool.poetry]
name = "jw_plyflatten"
version = "0.1.0"
description = "Take a series of ply files and produce a digital elevation map"
authors = ["JaeWangL <jnso5072@outlook.kr>"]

[tool.black]
line-length = 100
target_version = ['py36', 'py37', 'py38', 'py39']

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.1"
affine = "^2.3.1"
plyfile = "^0.7.4"
rasterio = "^1.3.0"
pyproj = "^3.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
