[tool.poetry]
name = "img2pdfscrpr"
version = "0.1"
description = "Image to PDF Web Scraper (tailored for Manga)"
authors = ["paytonward6 <72841140+paytonward6@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

beautifulsoup4 = "^4.11.1"

Pillow = "^9.2.0"

requests = "^2.28.1"

pathlib = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
img2pdfscrpr = 'img2pdfscrpr.img2pdfscrpr:main'
