[package]
name = "sql_to_query"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sql_to_query"
crate-type = ["cdylib"]

[dependencies]
elastic_query = "0.4.4"
pyo3 = { version = "0.16.5", features = ["extension-module"] }
