[tool.poetry]
name = "continual"
version = "v0.5.66"
description = "Operational AI for the Modern Data Stack"
authors = ["Continual <support@continual.ai>"]
readme = "README.md"

[tool.poetry.scripts]
continual = 'continual.python.cli.cli:cli'

[tool.poetry.dependencies]
python = ">=3.7"
grpcio = ">=1.27.1"
pandas = ">=1.0.1"
pyyaml = ">=5.4"
requests = ">=2.23.0"
click = "8.0.4"
tabulate = ">=0.8.6"
halo = ">=0.0.30"
grpcio_status = ">=1.31.0"
gitpython = ">=3.1.7"
humanize = ">=2.5.0"
typer = "0.4.0"
yamale = ">=4.0.0"
tqdm = ">=4.54.1"
pandas-gbq = ">=0.14.1"
pytz = ">=2020.5"
fsspec = "2022.3"
rich = ">=9.13.0"
cron-descriptor = ">=1.2.24"
google-cloud-storage = ">=1.33.0"
sqlparse = ">=0.4.2"
toml = ">=0.10.2"
poetry = ">=0.12"
protobuf = ">=3.12.0, <3.19.0"

[tool.poetry.dev-dependencies]
pytest = ">=5.2"

[build-system]
requires = ["poetry>=0.12"]
