[project]
name = "groof"
version = "0.1.0"
description = ""
authors = [
    { name = "levch", email = "levchenko.d.a1998@gmail.com" },
]
dependencies = [
    "mongoengine>=0.24.2",
    "envparse>=0.2.0",
    "requests>=2.28.1",
    "pyyaml>=6.0",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"

[tool.pdm]
